title: "EvanZhao's Tech Blog"
description: "Sharing knowledge about backend development, AI, and system design."
baseurl: ""  # Keep Empty
url: "https://evanzhao119.github.io"  # GitHub Pages 的 URL

# 主题设置
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-paginate

author:
  name: "Evan Zhao"
  avatar: "/assets/images/avatar.png" 
  bio: "Technical Manager / Senior Software Engineer / Java, Python, Architecture, Big Data / Scalable System Design"
  location: "Canada"
  email: "evanzhao119@gmail.com"
  github: "EvanZhao119"
  linkedin: "evan-zhao-software"
  # twitter: "evanzhao_dev"

exclude:
  - CHANGELOG.md

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-D5FXLGMCXD"
    anonymize_ip: false # true/false

# 主页分页配置
paginate: 5  # 每页显示的文章数量
paginate_path: "/page/:num/"  # 主页的分页路径

# 分类页面配置
category_archive:
  type: liquid
  path: /
